import type {
  KpiPeriod,
  KpiData,
  KpiSubmission,
  SectionKey,
  SectionStatus,
  Notification,
} from './types';

// ─── Periods ──────────────────────────────────────────────────────────────
export const periods: KpiPeriod[] = [
  { id: '2026-01', month: 1, year: 2026, label: 'January 2026' },
  { id: '2026-02', month: 2, year: 2026, label: 'February 2026' },
  { id: '2026-03', month: 3, year: 2026, label: 'March 2026' },
  { id: '2026-04', month: 4, year: 2026, label: 'April 2026' },
  { id: '2026-05', month: 5, year: 2026, label: 'May 2026' },
  { id: '2026-06', month: 6, year: 2026, label: 'June 2026' },
];

// ─── Default empty KPI data ──────────────────────────────────────────────
export const emptyKpiData: KpiData = {
  faculty: { profCount: 0, assocProfCount: 0, asstProfCount: 0, resignedLastMonth: 0, studentFacultyRatio: '' },
  lms: { lessonPlansNotInLms: 0, facultyNamesNotInLms: [], facultyLessThan5Items: 0 },
  latePunchIn: { latePunchInsLastMonth: 0 },
  facultyPublications: { q1Publications: 0, q2Publications: 0, otherApprovedJournals: 0, conferencePapers: 0, q1UnderPreparation: 0, q2UnderPreparation: 0, journalUnderPreparation: 0, facultyNilPublications: 0 },
  studentPublications: { q1Publications: 0, q2Publications: 0, otherApprovedJournals: 0, conferencePapers: 0, q1UnderPreparation: 0, q2UnderPreparation: 0, journalUnderPreparation: 0, projectsWithoutPublications: 0 },
  fundedProjects: { projectsUnderExecution: 0, proposalsUnderPreparation: 0 },
  phdGuideship: { eligibleNotRegistered: 0, namesEligibleNotRegistered: [], registeredGuides: 0, guidesWithNilStudents: 0 },
  mous: { activeMous: 0, mou1Activity: '', mou2Activity: '', mou3Activity: '', mouSummaries: [] },
  fdp: { facultyWithFdp: 0, facultyNilFdp: 0, totalFdpHours: 0 },
  placement: { totalWithOffers: 0, totalWithoutOffers: 0, ctcAbove20L: 0, ctc10to20L: 0, ctc6to10L: 0, ctcBelow6L: 0 },
  awardsFaculty: { totalAwards: 0 },
  awardsStudents: { academicHackathonAwards: 0, sportsMusicAwards: 0 },
  consultancy: { consultanciesUnderExecution: 0, newConsultanciesThisMonth: 0 },
  partialDelivery: { subjectsWithPd: 0, totalPdHours: 0, expertsEngaging: 0 },
  patentsIpr: { patentsFiled: 0, patentsPublished: 0, patentsGranted: 0 },
};

const allCompleted: Record<SectionKey, SectionStatus> = {
  faculty: 'completed', lms: 'completed', latePunchIn: 'completed',
  facultyPublications: 'completed', studentPublications: 'completed',
  fundedProjects: 'completed', phdGuideship: 'completed', mous: 'completed',
  fdp: 'completed', placement: 'completed', awardsFaculty: 'completed',
  awardsStudents: 'completed', consultancy: 'completed',
  partialDelivery: 'completed', patentsIpr: 'completed',
};

const allNotStarted: Record<SectionKey, SectionStatus> = {
  faculty: 'not_started', lms: 'not_started', latePunchIn: 'not_started',
  facultyPublications: 'not_started', studentPublications: 'not_started',
  fundedProjects: 'not_started', phdGuideship: 'not_started', mous: 'not_started',
  fdp: 'not_started', placement: 'not_started', awardsFaculty: 'not_started',
  awardsStudents: 'not_started', consultancy: 'not_started',
  partialDelivery: 'not_started', patentsIpr: 'not_started',
};

// ─── Mock KPI Data for each period ───────────────────────────────────────
const mockDataByPeriod: Record<string, KpiData> = {
  '2026-01': {
    faculty: { profCount: 8, assocProfCount: 12, asstProfCount: 25, resignedLastMonth: 0, studentFacultyRatio: '15:1' },
    lms: { lessonPlansNotInLms: 5, facultyNamesNotInLms: ['Dr. Amit Shah', 'Dr. Priya Desai', 'Dr. Raj Patel', 'Dr. Sonal Mehta', 'Dr. Vikram Singh'], facultyLessThan5Items: 8 },
    latePunchIn: { latePunchInsLastMonth: 6 },
    facultyPublications: { q1Publications: 2, q2Publications: 1, otherApprovedJournals: 3, conferencePapers: 4, q1UnderPreparation: 5, q2UnderPreparation: 3, journalUnderPreparation: 2, facultyNilPublications: 12 },
    studentPublications: { q1Publications: 1, q2Publications: 0, otherApprovedJournals: 2, conferencePapers: 3, q1UnderPreparation: 4, q2UnderPreparation: 2, journalUnderPreparation: 1, projectsWithoutPublications: 18 },
    fundedProjects: { projectsUnderExecution: 3, proposalsUnderPreparation: 5 },
    phdGuideship: { eligibleNotRegistered: 4, namesEligibleNotRegistered: ['Dr. Neha Gupta', 'Dr. Rahul Verma', 'Dr. Sanjay Kumar', 'Dr. Meera Iyer'], registeredGuides: 8, guidesWithNilStudents: 2 },
    mous: { activeMous: 5, mou1Activity: 'Guest lecture by TCS on Cloud Computing', mou2Activity: 'Joint research proposal submitted with ISRO', mou3Activity: 'Student internship drive with Infosys', mouSummaries: ['TCS — Cloud & AI training', 'ISRO — Space tech research', 'Infosys — Internship pipeline', 'Microsoft — Azure lab setup', 'IBM — Quantum computing workshop'] },
    fdp: { facultyWithFdp: 15, facultyNilFdp: 30, totalFdpHours: 120 },
    placement: { totalWithOffers: 85, totalWithoutOffers: 35, ctcAbove20L: 5, ctc10to20L: 15, ctc6to10L: 35, ctcBelow6L: 30 },
    awardsFaculty: { totalAwards: 3 },
    awardsStudents: { academicHackathonAwards: 7, sportsMusicAwards: 4 },
    consultancy: { consultanciesUnderExecution: 2, newConsultanciesThisMonth: 1 },
    partialDelivery: { subjectsWithPd: 4, totalPdHours: 32, expertsEngaging: 3 },
    patentsIpr: { patentsFiled: 2, patentsPublished: 1, patentsGranted: 0 },
  },
  '2026-02': {
    faculty: { profCount: 8, assocProfCount: 12, asstProfCount: 25, resignedLastMonth: 1, studentFacultyRatio: '15:1' },
    lms: { lessonPlansNotInLms: 4, facultyNamesNotInLms: ['Dr. Amit Shah', 'Dr. Priya Desai', 'Dr. Raj Patel', 'Dr. Sonal Mehta'], facultyLessThan5Items: 7 },
    latePunchIn: { latePunchInsLastMonth: 5 },
    facultyPublications: { q1Publications: 4, q2Publications: 2, otherApprovedJournals: 4, conferencePapers: 6, q1UnderPreparation: 4, q2UnderPreparation: 3, journalUnderPreparation: 3, facultyNilPublications: 10 },
    studentPublications: { q1Publications: 2, q2Publications: 1, otherApprovedJournals: 3, conferencePapers: 5, q1UnderPreparation: 3, q2UnderPreparation: 2, journalUnderPreparation: 2, projectsWithoutPublications: 15 },
    fundedProjects: { projectsUnderExecution: 4, proposalsUnderPreparation: 4 },
    phdGuideship: { eligibleNotRegistered: 3, namesEligibleNotRegistered: ['Dr. Neha Gupta', 'Dr. Rahul Verma', 'Dr. Sanjay Kumar'], registeredGuides: 9, guidesWithNilStudents: 2 },
    mous: { activeMous: 5, mou1Activity: 'TCS workshop on DevOps practices', mou2Activity: 'ISRO project milestone review', mou3Activity: 'Infosys campus hiring round 1', mouSummaries: ['TCS — DevOps training', 'ISRO — Project milestone 2', 'Infosys — Campus hiring', 'Microsoft — Azure certification', 'IBM — Research fellowship'] },
    fdp: { facultyWithFdp: 20, facultyNilFdp: 25, totalFdpHours: 180 },
    placement: { totalWithOffers: 92, totalWithoutOffers: 28, ctcAbove20L: 6, ctc10to20L: 18, ctc6to10L: 38, ctcBelow6L: 30 },
    awardsFaculty: { totalAwards: 5 },
    awardsStudents: { academicHackathonAwards: 9, sportsMusicAwards: 5 },
    consultancy: { consultanciesUnderExecution: 3, newConsultanciesThisMonth: 1 },
    partialDelivery: { subjectsWithPd: 5, totalPdHours: 48, expertsEngaging: 4 },
    patentsIpr: { patentsFiled: 3, patentsPublished: 1, patentsGranted: 1 },
  },
  '2026-03': {
    faculty: { profCount: 8, assocProfCount: 13, asstProfCount: 24, resignedLastMonth: 0, studentFacultyRatio: '15:1' },
    lms: { lessonPlansNotInLms: 3, facultyNamesNotInLms: ['Dr. Amit Shah', 'Dr. Priya Desai', 'Dr. Raj Patel'], facultyLessThan5Items: 5 },
    latePunchIn: { latePunchInsLastMonth: 4 },
    facultyPublications: { q1Publications: 7, q2Publications: 3, otherApprovedJournals: 5, conferencePapers: 8, q1UnderPreparation: 3, q2UnderPreparation: 4, journalUnderPreparation: 2, facultyNilPublications: 8 },
    studentPublications: { q1Publications: 3, q2Publications: 2, otherApprovedJournals: 4, conferencePapers: 6, q1UnderPreparation: 3, q2UnderPreparation: 3, journalUnderPreparation: 2, projectsWithoutPublications: 12 },
    fundedProjects: { projectsUnderExecution: 5, proposalsUnderPreparation: 3 },
    phdGuideship: { eligibleNotRegistered: 2, namesEligibleNotRegistered: ['Dr. Neha Gupta', 'Dr. Rahul Verma'], registeredGuides: 10, guidesWithNilStudents: 1 },
    mous: { activeMous: 6, mou1Activity: 'TCS hackathon sponsorship', mou2Activity: 'ISRO summer internship placement', mou3Activity: 'New MoU signed with Wipro for R&D', mouSummaries: ['TCS — Hackathon partnership', 'ISRO — Summer internship', 'Infosys — Mentoring program', 'Microsoft — Azure workshops', 'IBM — Quantum research lab', 'Wipro — R&D collaboration'] },
    fdp: { facultyWithFdp: 28, facultyNilFdp: 17, totalFdpHours: 260 },
    placement: { totalWithOffers: 98, totalWithoutOffers: 22, ctcAbove20L: 8, ctc10to20L: 20, ctc6to10L: 40, ctcBelow6L: 30 },
    awardsFaculty: { totalAwards: 7 },
    awardsStudents: { academicHackathonAwards: 12, sportsMusicAwards: 6 },
    consultancy: { consultanciesUnderExecution: 3, newConsultanciesThisMonth: 0 },
    partialDelivery: { subjectsWithPd: 6, totalPdHours: 72, expertsEngaging: 5 },
    patentsIpr: { patentsFiled: 4, patentsPublished: 2, patentsGranted: 1 },
  },
  '2026-04': {
    faculty: { profCount: 9, assocProfCount: 13, asstProfCount: 24, resignedLastMonth: 1, studentFacultyRatio: '14:1' },
    lms: { lessonPlansNotInLms: 2, facultyNamesNotInLms: ['Dr. Amit Shah', 'Dr. Priya Desai'], facultyLessThan5Items: 4 },
    latePunchIn: { latePunchInsLastMonth: 3 },
    facultyPublications: { q1Publications: 10, q2Publications: 5, otherApprovedJournals: 6, conferencePapers: 10, q1UnderPreparation: 2, q2UnderPreparation: 4, journalUnderPreparation: 3, facultyNilPublications: 6 },
    studentPublications: { q1Publications: 5, q2Publications: 3, otherApprovedJournals: 5, conferencePapers: 8, q1UnderPreparation: 2, q2UnderPreparation: 3, journalUnderPreparation: 2, projectsWithoutPublications: 10 },
    fundedProjects: { projectsUnderExecution: 5, proposalsUnderPreparation: 4 },
    phdGuideship: { eligibleNotRegistered: 2, namesEligibleNotRegistered: ['Dr. Neha Gupta', 'Dr. Rahul Verma'], registeredGuides: 10, guidesWithNilStudents: 1 },
    mous: { activeMous: 6, mou1Activity: 'TCS tech talk series launched', mou2Activity: 'ISRO data access agreement signed', mou3Activity: 'Wipro lab inauguration', mouSummaries: ['TCS — Tech talk series', 'ISRO — Data access agreement', 'Infosys — Skill certification', 'Microsoft — Imagine Cup mentoring', 'IBM — Faculty exchange', 'Wipro — Lab inauguration'] },
    fdp: { facultyWithFdp: 32, facultyNilFdp: 14, totalFdpHours: 340 },
    placement: { totalWithOffers: 102, totalWithoutOffers: 18, ctcAbove20L: 10, ctc10to20L: 22, ctc6to10L: 42, ctcBelow6L: 28 },
    awardsFaculty: { totalAwards: 9 },
    awardsStudents: { academicHackathonAwards: 15, sportsMusicAwards: 8 },
    consultancy: { consultanciesUnderExecution: 4, newConsultanciesThisMonth: 1 },
    partialDelivery: { subjectsWithPd: 7, totalPdHours: 96, expertsEngaging: 6 },
    patentsIpr: { patentsFiled: 5, patentsPublished: 3, patentsGranted: 1 },
  },
  '2026-05': {
    faculty: { profCount: 9, assocProfCount: 13, asstProfCount: 23, resignedLastMonth: 1, studentFacultyRatio: '14:1' },
    lms: { lessonPlansNotInLms: 2, facultyNamesNotInLms: ['Dr. Amit Shah', 'Dr. Priya Desai'], facultyLessThan5Items: 3 },
    latePunchIn: { latePunchInsLastMonth: 4 },
    facultyPublications: { q1Publications: 12, q2Publications: 7, otherApprovedJournals: 7, conferencePapers: 12, q1UnderPreparation: 2, q2UnderPreparation: 3, journalUnderPreparation: 2, facultyNilPublications: 5 },
    studentPublications: { q1Publications: 6, q2Publications: 4, otherApprovedJournals: 5, conferencePapers: 9, q1UnderPreparation: 2, q2UnderPreparation: 2, journalUnderPreparation: 1, projectsWithoutPublications: 8 },
    fundedProjects: { projectsUnderExecution: 6, proposalsUnderPreparation: 3 },
    phdGuideship: { eligibleNotRegistered: 1, namesEligibleNotRegistered: ['Dr. Neha Gupta'], registeredGuides: 11, guidesWithNilStudents: 1 },
    mous: { activeMous: 7, mou1Activity: 'TCS AI bootcamp for students', mou2Activity: 'ISRO project phase 2 kick-off', mou3Activity: 'New MoU with Amazon for cloud labs', mouSummaries: ['TCS — AI bootcamp', 'ISRO — Phase 2 research', 'Infosys — Placement drive', 'Microsoft — Azure research credits', 'IBM — Quantum research paper', 'Wipro — Faculty training', 'Amazon — Cloud lab setup'] },
    fdp: { facultyWithFdp: 35, facultyNilFdp: 10, totalFdpHours: 420 },
    placement: { totalWithOffers: 108, totalWithoutOffers: 12, ctcAbove20L: 12, ctc10to20L: 25, ctc6to10L: 43, ctcBelow6L: 28 },
    awardsFaculty: { totalAwards: 11 },
    awardsStudents: { academicHackathonAwards: 18, sportsMusicAwards: 9 },
    consultancy: { consultanciesUnderExecution: 4, newConsultanciesThisMonth: 0 },
    partialDelivery: { subjectsWithPd: 8, totalPdHours: 120, expertsEngaging: 6 },
    patentsIpr: { patentsFiled: 6, patentsPublished: 3, patentsGranted: 2 },
  },
  '2026-06': {
    faculty: { profCount: 9, assocProfCount: 14, asstProfCount: 23, resignedLastMonth: 0, studentFacultyRatio: '14:1' },
    lms: { lessonPlansNotInLms: 1, facultyNamesNotInLms: ['Dr. Amit Shah'], facultyLessThan5Items: 2 },
    latePunchIn: { latePunchInsLastMonth: 3 },
    facultyPublications: { q1Publications: 14, q2Publications: 9, otherApprovedJournals: 8, conferencePapers: 14, q1UnderPreparation: 1, q2UnderPreparation: 3, journalUnderPreparation: 2, facultyNilPublications: 4 },
    studentPublications: { q1Publications: 7, q2Publications: 5, otherApprovedJournals: 6, conferencePapers: 10, q1UnderPreparation: 1, q2UnderPreparation: 2, journalUnderPreparation: 1, projectsWithoutPublications: 6 },
    fundedProjects: { projectsUnderExecution: 7, proposalsUnderPreparation: 3 },
    phdGuideship: { eligibleNotRegistered: 1, namesEligibleNotRegistered: ['Dr. Neha Gupta'], registeredGuides: 11, guidesWithNilStudents: 0 },
    mous: { activeMous: 7, mou1Activity: 'TCS placement partnership renewed', mou2Activity: 'ISRO satellite data analysis project', mou3Activity: 'Amazon AWS certification program started', mouSummaries: ['TCS — Placement partnership', 'ISRO — Satellite data analysis', 'Infosys — Student mentoring', 'Microsoft — Research grants', 'IBM — Faculty fellowship', 'Wipro — Industry project', 'Amazon — AWS certifications'] },
    fdp: { facultyWithFdp: 38, facultyNilFdp: 8, totalFdpHours: 500 },
    placement: { totalWithOffers: 112, totalWithoutOffers: 8, ctcAbove20L: 14, ctc10to20L: 28, ctc6to10L: 44, ctcBelow6L: 26 },
    awardsFaculty: { totalAwards: 13 },
    awardsStudents: { academicHackathonAwards: 22, sportsMusicAwards: 11 },
    consultancy: { consultanciesUnderExecution: 5, newConsultanciesThisMonth: 1 },
    partialDelivery: { subjectsWithPd: 8, totalPdHours: 144, expertsEngaging: 7 },
    patentsIpr: { patentsFiled: 7, patentsPublished: 4, patentsGranted: 2 },
  },
};

// ─── Submissions ─────────────────────────────────────────────────────────
export const initialSubmissions: Record<string, KpiSubmission> = {
  '2026-01': { periodId: '2026-01', data: mockDataByPeriod['2026-01'], sectionStatuses: { ...allCompleted }, lastUpdated: '2026-01-30T18:00:00Z', submittedAt: '2026-01-31T09:00:00Z' },
  '2026-02': { periodId: '2026-02', data: mockDataByPeriod['2026-02'], sectionStatuses: { ...allCompleted }, lastUpdated: '2026-02-27T18:00:00Z', submittedAt: '2026-02-28T09:00:00Z' },
  '2026-03': { periodId: '2026-03', data: mockDataByPeriod['2026-03'], sectionStatuses: { ...allCompleted }, lastUpdated: '2026-03-30T18:00:00Z', submittedAt: '2026-03-31T09:00:00Z' },
  '2026-04': { periodId: '2026-04', data: mockDataByPeriod['2026-04'], sectionStatuses: { ...allCompleted }, lastUpdated: '2026-04-29T18:00:00Z', submittedAt: '2026-04-30T09:00:00Z' },
  '2026-05': { periodId: '2026-05', data: mockDataByPeriod['2026-05'], sectionStatuses: { ...allCompleted }, lastUpdated: '2026-05-30T18:00:00Z', submittedAt: '2026-05-31T09:00:00Z' },
  '2026-06': {
    periodId: '2026-06',
    data: mockDataByPeriod['2026-06'],
    sectionStatuses: {
      ...allNotStarted,
      faculty: 'completed',
      lms: 'completed',
      latePunchIn: 'completed',
      facultyPublications: 'in_progress',
      studentPublications: 'in_progress',
      fundedProjects: 'completed',
      placement: 'completed',
      mous: 'in_progress',
    },
    lastUpdated: '2026-06-19T14:30:00Z',
  },
};

// ─── Notifications ────────────────────────────────────────────────────────
export const initialNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'kpi_reminder',
    message: 'KPI data for June 2026 not yet fully submitted — 7 sections remaining.',
    severity: 'error',
    timestamp: '2026-06-20T09:00:00Z',
    read: false,
  },
  {
    id: 'n2',
    type: 'compliance',
    message: '1 faculty member (Dr. Amit Shah) has lesson plans NOT uploaded to LMS.',
    severity: 'warning',
    timestamp: '2026-06-19T14:00:00Z',
    read: false,
  },
  {
    id: 'n3',
    type: 'research',
    message: '4 faculty members have nil publications since January 2026.',
    severity: 'warning',
    timestamp: '2026-06-18T11:00:00Z',
    read: false,
  },
  {
    id: 'n4',
    type: 'compliance',
    message: 'Dr. Neha Gupta is eligible for PhD guideship but has not registered.',
    severity: 'warning',
    timestamp: '2026-06-17T16:00:00Z',
    read: true,
  },
  {
    id: 'n5',
    type: 'kpi_reminder',
    message: 'MoU activities for 3 MoUs have not been logged this month.',
    severity: 'warning',
    timestamp: '2026-06-16T10:00:00Z',
    read: true,
  },
  {
    id: 'n6',
    type: 'system',
    message: 'May 2026 KPI report submitted successfully on 31 May 2026.',
    severity: 'info',
    timestamp: '2026-05-31T09:00:00Z',
    read: true,
  },
  {
    id: 'n7',
    type: 'research',
    message: '8 faculty with nil FDP hours — consider scheduling development programs.',
    severity: 'warning',
    timestamp: '2026-06-15T09:00:00Z',
    read: false,
  },
  {
    id: 'n8',
    type: 'system',
    message: '3 faculty members punched in after 09:15 last month.',
    severity: 'info',
    timestamp: '2026-06-14T08:00:00Z',
    read: true,
  },
  {
    id: 'n9',
    type: 'compliance',
    message: '6 student projects have no associated publications yet.',
    severity: 'warning',
    timestamp: '2026-06-13T11:30:00Z',
    read: false,
  },
  {
    id: 'n10',
    type: 'system',
    message: 'New MoU with Amazon signed — remember to log monthly activities.',
    severity: 'info',
    timestamp: '2026-06-10T15:00:00Z',
    read: true,
  },
];

export { mockDataByPeriod };
